apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-dev
  region: us-east-1

iam:
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::897729141306:policy/AWSLoadBalancerControllerIAMPolicy
      approve: true
