apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: backend
  namespace: expense
spec:
  serviceRef:
    name: backend # route traffic to the awesome-service
    port: 80
  targetGroupARN: {{ .Values.tgb.arn }}
  targetType: ip