deployment:
  imageVersion: IMAGE_VERSION
  imageURL: 897729141306.dkr.ecr.us-east-1.amazonaws.com/expense-dev-frontend
hpa: 
  cpuUtilization: 70
  enabled: true
tgb:
  arn: arn:aws:elasticloadbalancing:us-east-1:897729141306:targetgroup/expense-dev-frontend/da553636bdb0f4a5
