deployment:
  imageVersion: IMAGE_VERSION
  imageURL: 897729141306.dkr.ecr.us-east-1.amazonaws.com/expense-dev-frontend
hpa: 
  cpuUtilization: 70
  enabled: true
# tgb:
#   arn: arn:aws:elasticloadbalancing:us-east-1:897729141306:targetgroup/expense-dev-frontend/3df984eef1962dd7 # replace with your target group ARN expense-dev-frontend
tgb:
  arn: "arn:aws:elasticloadbalancing:us-east-1:897729141306:targetgroup/your-target-group-name/your-target-group-id"
